version: '3.8'
services:
  api-gateway:
    image: apigatewaymicroservice
    build:
      context: .
      dockerfile: src/APIGatewayMicroService/Dockerfile
    volumes:
      #- ./LocalNuGetFeed:/root/.nuget/packages
      - /src/Shared/SharedOutput
      - /packages
      - /certs:/app/certs

    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:8081;http://+:8080"
      

    # depends_on:
    #   - authentication-microservice
    #   - coding-company-microservice
    #   - common-microservice
    #   - employee-microservice
    #   - inventory-microservice
    #   - school-library-microservice
    #   - ui-microservice

  # authentication-microservice:
  #   image: authenticationmicroservice
  #   build:
  #     context: .
  #     dockerfile: src/AuthenticationMicroService/Dockerfile
  #   ports:
  #     - "8082:80"
  #     - "8083:443"

  
  # coding-company-microservice:
  #   image: codingcompanymicroservice
  #   build:
  #     context: .
  #     dockerfile: src/MasterMicroService/CodingCompanyMicroService/Dockerfile
  #   ports:
  #     - "8084:80"
  #     - "8085:443"
  
  # common-microservice:
  #   image: commonmicroservice
  #   build:
  #     context: .
  #     dockerfile: src/SchoolManagementMicroServiceCollection/CommonMicroService/Dockerfile
  #   ports:
  #     - "8086:80"
  #     - "8087:443"
  
  # employee-microservice:
  #   image: employeemicroservice
  #   build:
  #     context: .
  #     dockerfile: src/SchoolManagementMicroServiceCollection/EmployeeMicroService/Dockerfile
  #   ports:
  #     - "8088:80"
  #     - "8090:443"

  # inventory-microservice:
  #   image: inventorymicroservice
  #   build:
  #     context: .
  #     dockerfile: src/SchoolManagementMicroServiceCollection/InventoryMicroService/Dockerfile
  #   ports:
  #     - "8091:80"
  #     - "8092:443"
  
  # school-library-microservice:
  #   image: schoollibrarymicroservice
  #   build:
  #     context: .
  #     dockerfile: src/SchoolManagementMicroServiceCollection/SchoolLibraryMicroService/Dockerfile
  #   ports:
  #     - "8093:80"
  #     - "8094:443"
  
  # ui-microservice:
  #   image: uimicroservice
  #   build:
  #     context: .
  #     dockerfile: src/UIMicroService/Dockerfile
  #   ports:
  #     - "8095:80"
  #     - "8096:443"
