using GenericFunction;
using ModelTemplates.Core.GenericModel;

namespace ModelTemplates.Persistence.Models.School.Inventory;


/// <summary>
/// Product Model is derived by Generic template which comprises of
/// completed and incomplete methods for Product Component
/// This Data Model is responsible to communicate between business logic 
/// and database table.
/// </summary>
public class ProductModel : BaseTemplate
{
    /// <summary>
    /// Name of the product
    /// </summary>
    public string ProductName { get; set; } = string.Empty;

    /// <summary>
    /// Product extra details
    /// </summary>
    public string Details { get; set; } = string.Empty;

    /// <summary>
    /// Bar-code provided by manufacturer
    /// </summary>
    public string? CompanyBarCode { get; set; } = "N/A";

    /// <summary>
    /// Bar-code generated by institute
    /// </summary>
    public string? CustomBarCode { get; set; } = "N/A";

    /// <summary>
    /// Unit qty measurement per box 
    /// </summary>
    public double UnitPerBox { get; set; } = 1;

    /// <summary>
    /// Image of the product.
    /// </summary>
    public byte[]? ProductImage { get; set; }

    /// <summary>
    /// Default save method, which will set Room record as per logged in UserId
    /// </summary>
    /// <param name="userId">Logged in User Id</param>
    public new void Save(string userId)
    {
        base.Save(userId);
        ProductName = ProductName.ToCamelCase();
        CompanyBarCode = CompanyBarCode == DefaultStringValue ? DefaultStringValue : CompanyBarCode;
        CompanyBarCode = CustomBarCode == DefaultStringValue ? DefaultStringValue : CustomBarCode;
        UnitPerBox = UnitPerBox < 0 ? 0 : UnitPerBox;
    }

    /// <summary>
    /// Default save method, which will set Room record as per logged in UserId
    /// </summary>
    /// <param name="userId">Logged in User Id</param>
    public new void Update(string userId)
    {
        this.Save(userId);
        base.Update();
    }
}

