using System.ComponentModel.DataAnnotations;

namespace VModelLayer.InventoryModule;

public class ProductVm : BaseVMTemplate
{

    /// <summary>
    /// Name of the product
    /// </summary>
    [Required(ErrorMessage = "Product name is required!")]
    public string ProductName { get; set; } = string.Empty;

    /// <summary>
    /// Product extra details
    /// </summary>
    public string Details { get; set; } = string.Empty;

    /// <summary>
    /// Barcode provided by manufacturer
    /// </summary>
    public string? CompanyBarCode { get; set; } = "0";

    /// <summary>
    /// Barcode generated by institute
    /// </summary>
    public string? CustomBarCode { get; set; } = "0";

    /// <summary>
    /// Unit qty measurement per box 
    /// </summary>
    public double UnitPerBox { get; set; } = 1;

    /// <summary>
    /// Image of the product.
    /// </summary>
    public string? UploadImage { get; set; }
    public string? ProductImage { get; set; }

}